-- lovable-cron-fallback-reviewed: CellPay sends no Cash App webhook; server-side settlement must poll pending sessions within minutes (480 runs/day, no-op when the queue is empty).
-- Fix B v2s, B-3 schedule (M3). PREPARED, NOT SENT. Run AFTER b1_pockyt_settlement.v2s.sql (M1) and after the
-- cashapp-settlement-sweep function is deployed (M2). Checked read-only Oct 3 19:45 CT: pg_cron 1.6.4 and pg_net 0.20.0
-- available, NOT installed (AD-1 may install pg_cron first tonight; IF NOT EXISTS covers that); supabase_vault 0.3.1
-- installed with NO secrets in it (so 'project_url' must be created here). The mode is NOT set here: it is the
-- fraud_controls row written by M1 ('shadow').
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

-- Lovable fills the two placeholders inside the migration; real values never go into chat, code comments or logs.
-- The sweep secret is generated by the database itself and never leaves it.
SELECT vault.create_secret(encode(extensions.gen_random_bytes(32), 'hex'), 'cashapp_sweep_secret');
SELECT vault.create_secret('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6aXNzc2Rkc3JobXh4d2p4d3VzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2NDU5NzEsImV4cCI6MjA5MTIyMTk3MX0.4WnZMSomVasXseKmRggL0zqsRi6mBuzo_jDfya-4iHc', 'cashapp_sweep_anon_key');
SELECT vault.create_secret('https://fzisssddsrhmxxwjxwus.supabase.co', 'project_url')
 WHERE NOT EXISTS (SELECT 1 FROM vault.secrets WHERE name = 'project_url');

SELECT cron.schedule(
  'cashapp-settlement-sweep',
  '*/3 * * * *',
  $job$
  SELECT net.http_post(
    url := (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'project_url') || '/functions/v1/cashapp-settlement-sweep',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'cashapp_sweep_anon_key'),
      'x-sweep-secret', (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'cashapp_sweep_secret')),
    body := '{}'::jsonb,
    timeout_milliseconds := 55000);
  $job$);

-- REVERT (R-job): SELECT cron.unschedule('cashapp-settlement-sweep');
-- (Cloud -> Jobs "Disable" is the instant equivalent. Leave pg_cron/pg_net installed: AD-1 / LP-2 may use them.)